-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TodoApi.Object.Todo exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import TodoApi.InputObject
import TodoApi.Interface
import TodoApi.Object
import TodoApi.Scalar
import TodoApi.ScalarCodecs
import TodoApi.Union


id : SelectionSet Int TodoApi.Object.Todo
id =
    Object.selectionForField "Int" "id" [] Decode.int


title : SelectionSet String TodoApi.Object.Todo
title =
    Object.selectionForField "String" "title" [] Decode.string


done : SelectionSet Bool TodoApi.Object.Todo
done =
    Object.selectionForField "Bool" "done" [] Decode.bool


userId : SelectionSet Int TodoApi.Object.Todo
userId =
    Object.selectionForField "Int" "userId" [] Decode.int


user :
    SelectionSet decodesTo TodoApi.Object.User
    -> SelectionSet decodesTo TodoApi.Object.Todo
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity
