-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TodoApi.Object.User exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import TodoApi.InputObject
import TodoApi.Interface
import TodoApi.Object
import TodoApi.Scalar
import TodoApi.ScalarCodecs
import TodoApi.Union


id : SelectionSet Int TodoApi.Object.User
id =
    Object.selectionForField "Int" "id" [] Decode.int


username : SelectionSet String TodoApi.Object.User
username =
    Object.selectionForField "String" "username" [] Decode.string


todos :
    SelectionSet decodesTo TodoApi.Object.Todo
    -> SelectionSet (List decodesTo) TodoApi.Object.User
todos object____ =
    Object.selectionForCompositeField "todos" [] object____ (Basics.identity >> Decode.list)
