-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TodoApi.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import TodoApi.InputObject
import TodoApi.Interface
import TodoApi.Object
import TodoApi.Scalar
import TodoApi.ScalarCodecs
import TodoApi.Union


type alias CreateTodoRequiredArguments =
    { title : String
    , userId : Int
    }


createTodo :
    CreateTodoRequiredArguments
    -> SelectionSet decodesTo TodoApi.Object.Todo
    -> SelectionSet decodesTo RootMutation
createTodo requiredArgs____ object____ =
    Object.selectionForCompositeField "createTodo" [ Argument.required "title" requiredArgs____.title Encode.string, Argument.required "userId" requiredArgs____.userId Encode.int ] object____ Basics.identity


type alias CreateUserRequiredArguments =
    { username : String }


createUser :
    CreateUserRequiredArguments
    -> SelectionSet decodesTo TodoApi.Object.User
    -> SelectionSet decodesTo RootMutation
createUser requiredArgs____ object____ =
    Object.selectionForCompositeField "createUser" [ Argument.required "username" requiredArgs____.username Encode.string ] object____ Basics.identity
