-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TodoApi.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import TodoApi.Scalar exposing (defaultCodecs)


type alias Id =
    TodoApi.Scalar.Id


codecs : TodoApi.Scalar.Codecs Id
codecs =
    TodoApi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
